//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Type_to_race_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public player()
        {
            this.Player_score = new HashSet<Player_score>();
        }
    
        public int PlayerId { get; set; }
        public string Player_name { get; set; }
        public string Player_email { get; set; }
        public string Player_password { get; set; }
        public Nullable<bool> C_Status { get; set; }
        public Nullable<int> Player_role { get; set; }
        public string ImageUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player_score> Player_score { get; set; }
    }
}
