//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Type_to_race_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player_score
    {
        public int Score_id { get; set; }
        public int wpm { get; set; }
        public int cpm { get; set; }
        public int timeelapsed { get; set; }
        public int Aquracy { get; set; }
        public int PlayerId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual player player { get; set; }
    }
}
