//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Type_to_race_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TypetoRaceEntities : DbContext
    {
        public TypetoRaceEntities()
            : base("name=TypetoRaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Player_score> Player_score { get; set; }
        public virtual DbSet<player> players { get; set; }
    
        public virtual ObjectResult<myhighscore_Result> myhighscore(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<myhighscore_Result>("myhighscore", idParameter);
        }
    
        public virtual ObjectResult<Top_3_Result> Top_3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Top_3_Result>("Top_3");
        }
    }
}
